version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: vercel-main
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: vercel-main
    schedule:
      interval: monthly
