const FLAGS: Record<string, string> = {
  Algeria: '🇩🇿',
  Argentina: '🇦🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Belgium: '🇧🇪',
  'Bosnia-Herzegovina': '🇧🇦',
  Brazil: '🇧🇷',
  Canada: '🇨🇦',
  'Cape Verde Islands': '🇨🇻',
  Colombia: '🇨🇴',
  'Congo DR': '🇨🇩',
  Croatia: '🇭🇷',
  Curaçao: '🇨🇼',
  Czechia: '🇨🇿',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Haiti: '🇭🇹',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  'Ivory Coast': '🇨🇮',
  Japan: '🇯🇵',
  Jordan: '🇯🇴',
  Mexico: '🇲🇽',
  Morocco: '🇲🇦',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Norway: '🇳🇴',
  Panama: '🇵🇦',
  Paraguay: '🇵🇾',
  Portugal: '🇵🇹',
  Qatar: '🇶🇦',
  'Saudi Arabia': '🇸🇦',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Senegal: '🇸🇳',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  Spain: '🇪🇸',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  'United States': '🇺🇸',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  Venezuela: '🇻🇪',
  'Costa Rica': '🇨🇷',
  Honduras: '🇭🇳',
  'El Salvador': '🇸🇻',
  Jamaica: '🇯🇲',
  Cuba: '🇨🇺',
  Guatemala: '🇬🇹',
  Peru: '🇵🇪',
  Chile: '🇨🇱',
  Bolivia: '🇧🇴',
  Nigeria: '🇳🇬',
  Cameroon: '🇨🇲',
  Mali: '🇲🇱',
  Serbia: '🇷🇸',
  Poland: '🇵🇱',
  Romania: '🇷🇴',
  Ukraine: '🇺🇦',
  Slovakia: '🇸🇰',
  Albania: '🇦🇱',
  Georgia: '🇬🇪',
  Slovenia: '🇸🇮',
  Wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Northern Ireland': '🏴',
  'Republic of Ireland': '🇮🇪',
  'New Caledonia': '🇳🇨',
  Bahrain: '🇧🇭',
  Kuwait: '🇰🇼',
  Indonesia: '🇮🇩',
  Thailand: '🇹🇭',
  Denmark: '🇩🇰',
  Hungary: '🇭🇺',
  Italy: '🇮🇹'
}

const NAMES_ES: Record<string, string> = {
  Algeria: 'Argelia',
  Argentina: 'Argentina',
  Australia: 'Australia',
  Austria: 'Austria',
  Belgium: 'Bélgica',
  'Bosnia-Herzegovina': 'Bosnia-Herzegovina',
  Brazil: 'Brasil',
  Canada: 'Canadá',
  'Cape Verde Islands': 'Cabo Verde',
  Colombia: 'Colombia',
  'Congo DR': 'Congo RD',
  Croatia: 'Croacia',
  Curaçao: 'Curazao',
  Czechia: 'República Checa',
  Ecuador: 'Ecuador',
  Egypt: 'Egipto',
  England: 'Inglaterra',
  France: 'Francia',
  Germany: 'Alemania',
  Ghana: 'Ghana',
  Haiti: 'Haití',
  Iran: 'Irán',
  Iraq: 'Irak',
  'Ivory Coast': 'Costa de Marfil',
  Japan: 'Japón',
  Jordan: 'Jordania',
  Mexico: 'México',
  Morocco: 'Marruecos',
  Netherlands: 'Países Bajos',
  'New Zealand': 'Nueva Zelanda',
  Norway: 'Noruega',
  Panama: 'Panamá',
  Paraguay: 'Paraguay',
  Portugal: 'Portugal',
  Qatar: 'Catar',
  'Saudi Arabia': 'Arabia Saudita',
  Scotland: 'Escocia',
  Senegal: 'Senegal',
  'South Africa': 'Sudáfrica',
  'South Korea': 'Corea del Sur',
  Spain: 'España',
  Sweden: 'Suecia',
  Switzerland: 'Suiza',
  Tunisia: 'Túnez',
  Turkey: 'Turquía',
  'United States': 'Estados Unidos',
  Uruguay: 'Uruguay',
  Uzbekistan: 'Uzbekistán',
  Venezuela: 'Venezuela',
  'Costa Rica': 'Costa Rica',
  Honduras: 'Honduras',
  'El Salvador': 'El Salvador',
  Jamaica: 'Jamaica',
  Cuba: 'Cuba',
  Guatemala: 'Guatemala',
  Peru: 'Perú',
  Chile: 'Chile',
  Bolivia: 'Bolivia',
  Nigeria: 'Nigeria',
  Cameroon: 'Camerún',
  Mali: 'Malí',
  Serbia: 'Serbia',
  Poland: 'Polonia',
  Romania: 'Rumanía',
  Ukraine: 'Ucrania',
  Slovakia: 'Eslovaquia',
  Albania: 'Albania',
  Georgia: 'Georgia',
  Slovenia: 'Eslovenia',
  Wales: 'Gales',
  'Northern Ireland': 'Irlanda del Norte',
  'Republic of Ireland': 'Irlanda',
  'New Caledonia': 'Nueva Caledonia',
  Bahrain: 'Baréin',
  Kuwait: 'Kuwait',
  Indonesia: 'Indonesia',
  Thailand: 'Tailandia',
  Denmark: 'Dinamarca',
  Hungary: 'Hungría',
  Italy: 'Italia'
}

const FLAGS_MAP = new Map(Object.entries(FLAGS))
const NAMES_MAP = new Map(Object.entries(NAMES_ES))

export function getFlag(teamName: string): string {
  return FLAGS_MAP.get(teamName) ?? '🏳️'
}

export function getTeamName(teamName: string): string {
  return NAMES_MAP.get(teamName) ?? teamName
}
