name: ncol-next

on:
  push:
    branches:
      - main

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.APP_NAME }}-${{ secrets.APP_STAGE }}-github
          aws-region: us-east-1
      - name: Deploy app
        run: |
          npm ci
          npx sst deploy --stage production
