name: ncol-next

on:
  push-branches:
    - [main]

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.APP_NAME}}-${{secret.APP_STAGE}}-github
          aws-region: sa-east-1
          role-duration-seconds: 14390 #adjust as needed for your build time and match Maximum session duration in the aws console
      - name: Deploy app
        run: |
          npm i && npx sst deploy --stage production
